{{- $microservicename := "app" }}
{{- if (index .Values $microservicename).ingress.enabled -}}
{{- $fullName := printf "%s-%s" (include "netris-controller.fullname" .) "graphite" -}}
{{- $servicePort := .Values.graphite.service.port -}}
{{- $ingressPath := (index .Values $microservicename).ingress.path -}}
{{- $ingressPathType := (index .Values $microservicename).ingress.pathType -}}
{{- $newAPI := .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" -}}
{{- if $newAPI -}}
apiVersion: networking.k8s.io/v1
{{- else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1/Ingress" }}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "netris-controller.labels" . | nindent 4 }}
    {{- printf "%s-%s" (include "netris-controller.selectorLabels" .) $microservicename | nindent 4 }}
{{- if (index .Values $microservicename).ingress.labels }}
{{ toYaml (index .Values $microservicename).ingress.labels | indent 4 }}
{{- end }}
  {{- if (index .Values $microservicename).ingress.annotations }}
  annotations:
    {{- range $key, $value := (index .Values $microservicename).ingress.annotations }}
    {{ $key }}: {{ tpl $value $ | quote }}
    {{- end }}
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  {{- end }}
spec:
  {{- if (index .Values $microservicename).ingress.ingressClassName }}
  ingressClassName: {{ (index .Values $microservicename).ingress.ingressClassName }}
  {{- end -}}
{{- if (index .Values $microservicename).ingress.tls }}
  tls:
{{ tpl (toYaml (index .Values $microservicename).ingress.tls) $ | indent 4 }}
{{- end }}
  rules:
  {{- if (index .Values $microservicename).ingress.hosts  }}
  {{- range (index .Values $microservicename).ingress.hosts }}
    - host: {{ tpl . $}}
      http:
        paths:
          - path: {{ trimSuffix "/" $ingressPath }}/dash(/|$)(.*)
            {{- if $newAPI }}
            pathType: {{ $ingressPathType }}
            {{- end }}
            backend:
              {{- if $newAPI }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $servicePort }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $servicePort }}
              {{- end }}
  {{- end }}
  {{- else }}
    - http:
        paths:
          - backend:
              {{- if $newAPI }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $servicePort }}
            pathType: {{ $ingressPathType }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $servicePort }}
              {{- end }}
          {{- if $ingressPath }}
            path: {{ trimSuffix "/" $ingressPath }}/dash(/|$)(.*)
            {{- end }}
  {{- end -}}
{{- end }}
