apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" (include "netris-controller.fullname" .) "web-session-secret" }}
  labels:
  {{- include "netris-controller.labels" . | nindent 4 }}
type: Opaque
data:
{{- ( include "web.session.secret" . ) | indent 2 -}}
