apiVersion: v2
name: netris-controller
description: A Helm chart for netris-controller

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.4.1

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: 3.4.1
home: https://netris.ai
icon: https://www.netris.ai/wp-content/uploads/2021/01/logo-300.png  # [todo] Change url to permalink
keywords:
  - netris
  - netops
  - network
sources:
  - https://github.com/netrisai/charts
maintainers:
  - name: netrisai
    email: devops@netris.ai
dependencies:
  - name: mariadb
    version: 9.6.1
    repository: https://raw.githubusercontent.com/bitnami/charts/eb5f9a9513d987b519f0ecd732e7031241c50328/bitnami
  - name: mongodb
    version: 10.9.1
    repository: https://raw.githubusercontent.com/bitnami/charts/eb5f9a9513d987b519f0ecd732e7031241c50328/bitnami
  - name: redis
    version: 12.8.3
    repository: https://raw.githubusercontent.com/bitnami/charts/eb5f9a9513d987b519f0ecd732e7031241c50328/bitnami
  - name: smtp
    version: 1.0.1
    repository: https://charts.ntppool.org
  - name: haproxy
    version: 1.1.3
    repository: https://haproxytech.github.io/helm-charts
    condition: haproxy.enabled
  - name: graphite
    version: 0.7.2
    repository: https://kiwigrid.github.io
